// <auto-generated />
namespace M183.Blog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddBaseStructure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBaseStructure));
        
        string IMigrationMetadata.Id
        {
            get { return "201801140955525_AddBaseStructure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
